name: Pull Request Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build launcher
      run: ./mill launcher.assembly
    - name: Build agent
      run: ./mill devbox.agent.assembly
    - name: Run tests
      run: ./mill devbox.test
    - name: Upload test logs
      uses: actions/upload-artifact@v2
      with:
        name: testlogs
        path: ./out/devbox/test/test/log
