name: Pull Request Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Symlink /dev/shm
      run: ln -s /dev/shm tmpfs
    - uses: actions/checkout@v2
      with:
        path: tmpfs/devbox
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build launcher
      run: ./mill launcher.assembly
      working-directory: ./tmpfs/devbox
    - name: Build agent
      run: ./mill devbox.agent.assembly
      working-directory: ./tmpfs/devbox
    - name: Run tests
      run: ./mill devbox.test
      working-directory: ./tmpfs/devbox
    - name: Upload test logs
      uses: actions/upload-artifact@v2
      with:
        name: testlogs
        path: ./tmpfs/devbox/out/devbox/test/test/log
