name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '0.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: ./mill launcher.assembly
      - name: Calculate SHA-1
        id: caculate_sha1
        run: echo "::set-output name=sha1::$(sha1sum ./out/launcher/assembly/dest/out.jar | cut -d " " -f 1)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }} (sha ${{ steps.caculate_sha1.outputs.sha1 }})
          draft: false
          prerelease: false
      - name: Upload devbox.jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/launcher/assembly/dest/out.jar
          asset_name: devbox.jar
          asset_content_type: application/zip